name: dependabot
on: 
  workflow_dispatch:

version: 2
updates:
  
  - package-ecosystem: "gomod"
    directory: "/super_calculator/"              
    schedule:
      interval: "daily"         
    open-pull-requests-limit: 5

 
  - package-ecosystem: "docker"
    directory: "/super_calculator/"               
    schedule:
      interval: "daily"          
    open-pull-requests-limit: 5
