name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:    

jobs:
  release:
    name: Release with GoReleaser and Docker
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 🔹 1. Checkout le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 🔹 2. Setup Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22' # adapte si nécessaire

      # 🔹 3. Install GoReleaser
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
          
      # 🔹 4. Run GoReleaser
      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      # 🔹 5. Login to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔹 6. Extract tag version (ex: 1.1.1)
      - name: Extract tag version
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 🔹 7. Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.VERSION }}
